# Generated by Django 4.1.1 on 2025-07-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='Rut')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Agente de ventas',
                'verbose_name_plural': 'Agentes de ventas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], max_length=10, verbose_name='Tipo de Persona')),
                ('nombre_razon_social', models.CharField(blank=True, max_length=200, verbose_name='Nombre o Razón Social')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('sitio_web', models.CharField(blank=True, max_length=100, verbose_name='Sitio Web')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.agenteventas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Dirección')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Dirección',
                'verbose_name_plural': 'Tipos de Dirección',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código Potal')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.tipodireccion', verbose_name='Tipo de Dirección')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
