# Generated by Django 4.1.1 on 2025-08-18 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_agenteventas_user_alter_cliente_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodireccion',
            options={'verbose_name': 'Tipo de Dirección', 'verbose_name_plural': 'Tipos de Direcciones'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='Rut'),
        ),
        migrations.CreateModel(
            name='ImportacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitosos', models.PositiveIntegerField(default=0)),
                ('fallidos', models.PositiveIntegerField(default=0)),
                ('errores', models.TextField(blank=True)),
                ('hash_archivo', models.CharField(max_length=64, unique=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
