# Generated by Django 4.1.1 on 2025-09-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_tipodireccion_options_alter_cliente_rut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Entidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.tipoentidad', verbose_name='Tipo de Entidad'),
        ),
    ]
